spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://127.0.0.1:3306/fancapital}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # MySQLDialect évite la requête information_schema.sequences (absent en MySQL/MariaDB < 10.6)
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC

